### ISSUE TITLE
add yaml annotations for consistent output formatting

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-client-go#46]
while doing dev work for synse v3 in the synse-cli, I noticed that in some cases, yaml formatting can be different than json formatting, e.g. (see the version section):

**JSON**
```json
[
  {
    "active": true,
    "id": "4032ffbe-80db-5aa5-b794-f35c88dff85c",
    "name": "emulator plugin",
    "description": "A plugin with emulated devices and data",
    "maintainer": "vaporio",
    "tag": "vaporio/emulator-plugin",
    "vcs": "",
    "version": {
      "plugin_version": "",
      "sdk_version": "",
      "build_date": "",
      "git_commit": "",
      "git_tag": "",
      "arch": "",
      "os": ""
    }
  }
]
```

**YAML**
```yaml
- active: true
  id: 4032ffbe-80db-5aa5-b794-f35c88dff85c
  name: emulator plugin
  description: A plugin with emulated devices and data
  maintainer: vaporio
  tag: vaporio/emulator-plugin
  vcs: ""
  version:
    pluginversion: ""
    sdkversion: ""
    builddate: ""
    gitcommit: ""
    gittag: ""
    arch: ""
    os: ""
```

This issue is to add annotations to the scheme types so yaml output will have the same keys as json output
